name       : unity-gtk-module
version    : 16.10.20160913
release    : 5
source     :
    - https://launchpad.net/ubuntu/+archive/primary/+files/unity-gtk-module_0.0.0+16.10.20160913.orig.tar.gz : 908f196ff53d15a0823a6530f7dd335759e46baa3f286d98f8342b211b0a011b
license    : LGPL-3.0
component  : desktop.library
summary    : GTK+ module to export menus over dbus
description: |
    GTK+ module to export menus over dbus
builddeps  :
    - pkgconfig(gtk+-3.0)
    - pkgconfig(gtk+-2.0)
    - pkgconfig(gtk-doc)
    - pkgconfig(x11)
setup      : |
    autoreconf -vfi
    mkdir unity-gtk-module-gtk3 && pushd unity-gtk-module-gtk3
    ../configure %CONFOPTS% --with-gtk=3 --disable-static
    %make
    popd    
build      : |
    mkdir unity-gtk-module-gtk2 && pushd unity-gtk-module-gtk2
    ../configure %CONFOPTS% --with-gtk=2 --disable-static
    %make
    popd
install    : |
    pushd unity-gtk-module-gtk3
    %make_install
    popd

    pushd unity-gtk-module-gtk2
    %make_install
    popd

    rm -rf $installdir/usr/share/upstart
    # Nuke systemd activator too
    rm -rf $installdir/usr/lib
