name       : unity-gtk-module
version    : 16.10.20160913
release    : 1
source     :
    - https://launchpad.net/ubuntu/+archive/primary/+files/unity-gtk-module_0.0.0+16.10.20160913.orig.tar.gz : 908f196ff53d15a0823a6530f7dd335759e46baa3f286d98f8342b211b0a011b
license    : LGPL-3.0
component  : desktop.library
summary    : GTK+ module to export menus over dbus
description: |
    GTK+ module to export menus over dbus
builddeps  :
    - pkgconfig(gtk+-3.0)
    - pkgconfig(gtk-doc)
    - pkgconfig(x11)
setup      : |
    %reconfigure --disable-static
build      : |
    %make
install    : |
    %make_install
    rm -rf $installdir/usr/share/upstart
    # Nuke systemd activator too
    rm -rf $installdir/usr/lib
